@ECHO off

SET ROOT=%~dp0
SET BUILD_DIR=%ROOT%\build

SET INCLUDE_DIR=-I%ROOT%\src
SET WARNINGS=/W4 /wd4996 /wd4577 /wd4065
SET DEFINITIONS=-DWIN32_LEAN_AND_MEAN -DNOMINMAX

SET FLAGS=%WARNINGS% %DEFINITIONS%
SET FLAGS=%FLAGS% /Zi /EHsc

SET OPTIMIZED=/O2
SET UNOPTIMIZED=/Od

if not exist %BUILD_DIR% mkdir %BUILD_DIR%

PUSHD %BUILD_DIR%
cl %FLAGS% %UNOPTIMIZED% -I%ROOT%\steam -I%ROOT% %ROOT%\djpad.cpp /link /SUBSYSTEM:WINDOWS %ROOT%\steam_api64.lib User32.lib
POPD
